# Uncomment the next line to define a global platform for your project
 platform :macos, '13.0'

# 关闭pod签名
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
         end
    end
  end
  #升级Xcode 15后编译报错
    #报错内容：
    #DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        end
    end
end

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'MediaLive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ffmpeg-kit-macos-full', '~> 4.4'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Masonry', '~> 1.1.0'

  # Pods for MediaLive

end
